### ISSUE TITLE
 Add practice examples before real answers begin

### ISSUE THREAD

**Issue by hideodaikoku** [keio-moe/song-test-api#2]
I think it would be ideal to add one example for each stylistic feature, taken from the Cantometric examples in “Songs of Earth” accessible at this site (after logging in as a guest):  https://dev.theglobaljukebox.org. If you have trouble scraping the songs from here you could also try to find them from within the ones I digitized and uploaded , but that will probably take longer. (PS: Please explore these training tapes, as they seem to be ideal training data for future machine-learning approaches!)
a.    Melodic range: Line 20, examples 3 (min), 4 (med), and 7 (max)
b.    Embellishment: Line 23, example 3 (max), 7 (med), and 4 (min)
c.    Rhythm: Line 11. Overall Rhythm Vocal, example 1 (max), 13 (med), and 14 (min)
d.    Solo/group: Line 1, example 1 (min) and 18 (max), then use Line 4 example 2 for a clear intermediate example
e.    Vocal width: Line 33, example 2 (min), 5 (med), and 6 (max)
f.    Tempo: Line 24, example 2 (min), 8 (med), and 3 (max)
I’d also group these together at the beginning as “Stylistic features”, 「様式的要素」then group the others at “Aesthetic features” 「美的要素」 and explain that we don’t give examples because these are more subjective and depend on the listener’s reaction「美的要素の関しては人それぞれの反応によって違うのでここで事例を載せない」

**Comment by hideodaikoku** [comment]
I messaged you about this on facebook. The repository for this is https://github.com/hideodaikoku/feat-explanation

**Comment by hideodaikoku** [comment]
@dsh0416 Updated the repository with more specific examples and normalized audio to 0dbFS

https://github.com/hideodaikoku/feat-explanation

**Comment by dsh0416** [comment]
Can you setup your repo with GitHub Pages? So that I could use iframe to show your webpage inside the explanation page

**Comment by hideodaikoku** [comment]
ok one sec

**Comment by hideodaikoku** [comment]
https://hideodaikoku.github.io/feat-explanation/

**Comment by hideodaikoku** [comment]
https://hideodaikoku.github.io/feat-explanation/

The last button at the bottom has a link that needs to be edited.
